import { ModeToggle } from "./components/mode-toggle";
import { ThemeProvider } from "./components/theme-provider";
import { Button } from "./components/ui/button";
import { Github, FileVideo, Upload } from "lucide-react";
import { Textarea } from "./components/ui/textarea";
import { Separator } from "./components/ui/separator";
import { Label } from "./components/ui/label";

export function App() {
  return (
    <div className="min-h-screen flex flex-col">
      <div className="px-6 py-3 flex items-center justify-between border-b">
        <img
          src="/public/logo.png"
          alt="Rausch.ai Icon"
          width={50}
          height={50}
        />

        <div className="flex items-center gap-3">
          <ThemeProvider defaultTheme="dark" storageKey="vite-ui-theme">
            <ModeToggle />
          </ThemeProvider>

          <a href="https://github.com/giovannibraaga" target="_blank">
            <Button variant="outline">
              <Github className="w-4 h-4 mr-2" />
              Github
            </Button>
          </a>
        </div>
      </div>

      <main className="flex-1 p-6 flex gap-6">
        <div className="flex flex-col flex-1 gap-4">
          <div className="grid grid-rows-2 gap-4 flex-1">
            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Include the AI prompt..."
            />
            <Textarea
              className="resize-none p-4 leading-relaxed"
              placeholder="Result generated by AI..."
              readOnly
            />
          </div>

          <p className="text-sm text-muted-foreground">
            Remember: You can use the{" "}
            <code className="text-[#1FB255]">{"{transcription}"}</code> variable
            in your prompt to add the content of the transcription from the
            selected video.
          </p>
        </div>

        <aside className="w-80 space-y-6">
          <form className="space-y-6">
            <label
              htmlFor="video"
              className="p-14 text-muted-foreground text-sm flex flex-col items-center justify-center gap-2 border border-dashed rounded-md aspect-video cursor-pointer hover:bg-primary/20"
            >
              Select a video
              <FileVideo className="w-4 h-4" />
            </label>

            <input
              type="file"
              id="video"
              accept="video/mp4"
              className="sr-only"
            />

            <Separator />

            <div className="space-y-1">
              <Label htmlFor="transcription_prompt">Transcription prompt</Label>
              <Textarea
                id="transcription_prompt"
                className="min-h-20 leading-relaxed"
                placeholder="Include key words that are mentioned in the video, separeted by commas ( , )"
              />

              <Button type="submit" className="w-full">
                Upload Video 
                <Upload className="w-4 h-4 ml-2"/>
              </Button>
            </div>
          </form>
        </aside>
      </main>
    </div>
  );
}
